### ISSUE TITLE
Blurry text

### ISSUE THREAD

**Issue by bigardone** [codrops/ModalWindowEffects#13]
Hi!
when the modal shows, it's content is blurry on Chrome and Safari. Is there a way of fixing this?
Thanks in advance!

**Comment by crnacura** [comment]
Hi,
the blurriness is caused by using transforms for centering the modal box on the screen. You can try to use flexbox instead. Have a look at the more recent Dialog Effects where we use a flexbox layout: https://github.com/codrops/DialogEffects/blob/master/css/dialog.css
You can try using the .md-modal as the flexbox container (it should span over all the viewport) and the .md-content as the modal box dynamic sized. I'm not sure if this will work for all of the effects but it's the right direction for switching to a flexbox layout. 
Hope it helps somehow,
cheers, ML

**Comment by bigardone** [comment]
Thanks @crnacura for your response :)
Is there a working demo for this?
Thanks again

**Comment by bigardone** [comment]
Never mind! It's working great right now, thank you very much!
